# Remote control 활성화 (kitty @ 명령 사용)
allow_remote_control yes
listen_on unix:/tmp/kitty-socket

tab_bar_style custom
tab_bar_min_tabs 1
tab_fade 1
tab_bar_edge top

background #F5F5F5
foreground #333333

map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard
map cmd+0x8 copy_to_clipboard
map cmd+0x9 paste_from_clipboard
